name: Automatize test 

on:
  push

jobs:
  test: 
    #Запуск системы на определенном ПО
    runs-on: ubuntu-latest
    #Шаги при запуске
    steps:
      - name: Check reposit
        uses: actions/checkout@v3


      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.tox-env == 'devel' && 3.12 || matrix.tox-env }}


      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Using Test
        run: pytest -v